name: DeployementPipe

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: debian-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
      - name: Build
        run: npm run build && rm -rf docs && mv build docs
